Added Filebeat configuration example
elastic/ent-search-monitoring pull request #7
Opened 2022-03-31 11:04 UTC by carlosdelest

- Add a Filebeat example configuration
-  Add a note in the ent-search-monitoring [readme](https://github.com/elastic/ent-search-monitoring/blob/main/README.md) that this filebeat example yml is available as a reference for users looking to configure data collection for their Enterprise Search logs.

2022-03-31 13:06 UTC, richkuz requested changes

2022-03-31 13:06 UTC, richkuz commented on filebeat/filebeat.yml
> +      - "<enterprise_search_dir>/logs/worker.log*"
```suggestion
      - "<enterprise_search_dir>/log/worker.log*"
```

2022-03-31 13:06 UTC, richkuz commented on filebeat/filebeat.yml
> +      - "<enterprise_search_dir>/logs/connectors.log*"
```suggestion
      - "<enterprise_search_dir>/log/connectors.log*"
```

2022-03-31 13:06 UTC, richkuz commented on filebeat/filebeat.yml
> +      - "<enterprise_search_dir>/logs/crawler.log*"
```suggestion
      - "<enterprise_search_dir>/log/crawler.log*"
```

2022-03-31 13:06 UTC, richkuz commented on filebeat/filebeat.yml
> +      - "<enterprise_search_dir>/logs/filebeat*"
```suggestion
      - "<enterprise_search_dir>/log/filebeat*"
```

2022-03-31 13:06 UTC, richkuz commented on filebeat/filebeat.yml
> +      - "<enterprise_search_dir>/logs/system.log*"
```suggestion
      - "<enterprise_search_dir>/log/system.log*"
```

2022-04-05 10:05 UTC, carlosdelest commented
I added an index template to allow this to become a data stream, and be aligned with what we have in Cloud. It's visible now in Kibana / Logs section.

Also improved multiline management and used the new `filestream` input type instead of the deprecated `log` type.

2022-04-05 20:29 UTC, richkuz requested changes
I got it working! 👍 

I added `ssl.verification_mode: none` to my Elasticsearch output config because I'm running 8.2 (secured, in Docker). I think it's OK to leave this part out; users can follow the link you provided for how to configure the Elasticsearch settings.

I also added this configuration because my Kibana is running secured by default:
```
setup.kibana:
  host: "https://localhost:5601"
  ssl.verification_mode: none
```

I set ssl verification_mode to `none` instead of specifying paths to the keys because I'm running Docker and didn't configure a local mount to access those files easily.

Kibana and ES are secure by default in 8.x, so it's probably best to assume the user should configure ssl settings. Here's a proposal:

```
# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  hosts: ["<elasticsearch_host>"] # e.g. https://localhost:9200
  username: "<elasticsearch_username>"
  password: "<elasticsearch_password>"
  # Index name for Enterprise Search logs
  index: "ent-search-logs-8"
  bulk_max_size: 50
  # Set to "none" if your Elasticsearch instance is not secured.
  ssl.verification_mode: full
  ssl.enabled: true
  ssl.certificate: "<path_to_elasticsearch_cert_pem>"
  ssl.key: "<path_to_elasticsearch_cert_key>"

setup.template:
  overwrite: false
  json:
    enabled: true
    path: "filebeat-template-8.json"
    name: "ent-search-logs-8"
  name: "ent-search-logs-8"
  pattern: "ent-search-logs-8*"

setup.ilm:
  policy_name: "ent-search-logs"

processors:
  - drop_event.when.has_fields:
      - labels.skip_ingest

# -------------------------------- Kibana Setup --------------------------------
setup.kibana:
  host: "<kibana_host>" # e.g. https://localhost:5601
  # Set to "none" if your Kibana instance is not secured.
  ssl.verification_mode: full
  ssl.enabled: true
  ssl.certificate: "<path_to_elasticsearch_cert_pem>"
  ssl.key: "<path_to_elasticsearch_cert_key>"
```

2022-04-05 20:29 UTC, richkuz commented on filebeat/filebeat.yml
> +      - "<enterprise-search-dir>log/app-server.log*"
```suggestion
      - "<enterprise-search-dir>/log/app-server.log*"
```

2022-04-05 20:29 UTC, richkuz commented on filebeat/filebeat.yml
> +      - "<enterprise-search-dir>log/connectors.log*"
```suggestion
      - "<enterprise-search-dir>/log/connectors.log*"
```

2022-04-05 20:29 UTC, richkuz commented on filebeat/filebeat.yml
> +      - "<enterprise-search-dir>log/crawler.log*"
```suggestion
      - "<enterprise-search-dir>/log/crawler.log*"
```

2022-04-05 20:29 UTC, richkuz commented on filebeat/filebeat.yml
> +      - "<enterprise-search-dir>log/filebeat.log*"
```suggestion
      - "<enterprise-search-dir>/log/filebeat.log*"
```

2022-04-05 20:29 UTC, richkuz commented on filebeat/filebeat.yml
> +      - "<enterprise-search-dir>log/system.log*"
```suggestion
      - "<enterprise-search-dir>/log/system.log*"
```

2022-04-05 20:29 UTC, richkuz commented on filebeat/README.md
> +2. Replace `filebeat.yml` file in the Filebeat install directory with the one in this directory
3. Copy `filebeat-template-8.json` from this directory into your Filebeat install directory.

2022-04-05 20:29 UTC, richkuz commented on filebeat/README.md
> +3. Customize `filebeat.yml` with the needed information
```suggestion
4. Customize `filebeat.yml` with the needed information
```

2022-04-05 20:29 UTC, richkuz commented on filebeat/README.md
> +4. Run [Filebeat setup assets](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html#setup-assets)
```suggestion
5. Run [Filebeat setup assets](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html#setup-assets)
```

2022-04-05 20:29 UTC, richkuz commented on filebeat/README.md
> +5. [Start Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html#start)
```suggestion
6. [Start Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation-configuration.html#start)
```

2022-04-06 20:24 UTC, richkuz approved these changes

2022-04-07 05:08 UTC, merged